### ISSUE TITLE
DRYing sessions

### ISSUE THREAD

**Issue by de-olagundoye** [de-olagundoye/WDI_Project_2_Wiki#1]
In terms of my erb's I'm using a layout template to yield the 'home' link to the header of every page like everyone else. I thought it would be cool if when the user is logged in, it would show the 'home' link and the 'log out' link on every page. If not, the links shown are 'home', 'log in', and 'sign up'. I got this working but I ended up having to add a *@loggedinuser = User.find(session[:user_id]) if session[:user_id]* variable to each GET request on my server. That's about 12 times...so far. Is there a way to prevent that? I tried making *@ loggedinuser* into a class variable in my server but that was a fun adventure to error-land.

**Comment by phlco** [comment]
No, that's how you do it. You have to look up the logged in user.
